# Generated by Django 5.2.8 on 2026-02-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=20)),
                ('experience_years', models.IntegerField()),
                ('consultion_fee', models.FloatField()),
                ('phone_no', models.CharField(max_length=20)),
            ],
        ),
    ]
