# Generated by Django 5.2.8 on 2026-02-18 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.department'),
        ),
    ]
