# Generated by Django 5.2.8 on 2026-03-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_dept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
